#!/bin/bash
#SBATCH --job-name=omp-strong-mandelbort.set
#SBATCH --partition=EPYC
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --mem=490G
#SBATCH --time=01:00:00

module load openMPI/4.1.5/gnu/12.2.1

cd /u/dssc/nbehrooz/proj3/

gcc -fopenmp omp-strong-mandelbrot.c -o omp-strong-mandelbrot.x -lm

for threads in 2 4 6 8 9 10 11 12 13 14 15 16 17 18 19 20 24 32 64 112 120 123 128; do
    OMP_NUM_THREADS=$threads ./omp-strong-mandelbrot.x 256 256 -2.75 -2 1.25 2 255
done